language: csharp
sudo: false

script: 
  - ./build.sh --target "Travis"
    
notifications:
  webhooks:
    urls:
      - https://requestbin.fullcontact.com/13sz1px1
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
